const RECEIVE_GAMES = 'app/games/RECEIVE_GAMES'
const REQUEST_GAMES = 'app/games/REQUEST_GAMES'
const EDIT_GAME = 'app/games/EDIT_GAME'
const REQUEST_UPDATE_GAME = 'app/games/REQUEST_UPDATE_GAME'
const SUCCESS_UPDATE_GAME = 'app/games/SUCCESS_UPDATE_GAME'
const SWITCH_SIDES = 'app/games/SWITCH_SIDES'
const DUPLICATE_GAME = 'app/games/DUPLICATE_GAME'

export {
  RECEIVE_GAMES,
  REQUEST_GAMES,
  EDIT_GAME,
  SUCCESS_UPDATE_GAME,
  REQUEST_UPDATE_GAME,
  SWITCH_SIDES,
  DUPLICATE_GAME
}
