const REQUEST_LEAGUES = 'app/leagues/REQUEST_LEAGUES'
const RECEIVE_LEAGUES = 'app/leagues/RECEIVE_LEAGUES'
const SET_CURRENT_LEAGUE_ID = 'app/leagues/SET_CURRENT_LEAGUE_ID'

export {
  REQUEST_LEAGUES,
  RECEIVE_LEAGUES,
  SET_CURRENT_LEAGUE_ID
}
